name: Deploy Frontend

on:
  push:
    branches: [master]

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Deploy to Production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            bash ~/webapps/helpinghandtutor/deploy_frontend.sh master prod

  deploy-dev:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Deploy to Development
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            bash ~/webapps/helpinghandtutor/deploy_frontend.sh master dev
